name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

env:
  EXTNAME: MarkdownPages
  MW_INSTALL_PATH: ${{ github.workspace }}

jobs:
  test:
    name: PHPUnit
    runs-on: ubuntu-latest
    env:
      MW_INSTALL_PATH: ${{ github.workspace }}/mediawiki
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1', '8.3' ]
        mediawiki: [ REL1_43 ]
    steps:
      - name: Setup Extension
        uses: actions/checkout@v6
      - name: Mediawiki PHPUnit
        uses: wikiteq/mediawiki-phpunit-action@master
        with:
          type: extension
          php: ${{ matrix.php }}
          mwbranch: ${{ matrix.mediawiki }}
          extension: ${{ env.EXTNAME }}

  style-php:
    name: Code Style (PHP)
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl
          coverage: none
          tools: composer, phpcs, phplint
      - name: Setup Extension
        uses: actions/checkout@v6
      - name: Setup Composer
        run: composer update
      - name: Lint
        run: phplint -w --exclude=vendor
      - name: PHP Code Sniffer
        run: vendor/bin/phpcs -sp --standard=.phpcs.xml .

  security:
    name: Static Analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mediawiki: [ REL1_43 ]
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, ast
          coverage: none
          tools: composer
      - name: Setup MediaWiki
        uses: actions/checkout@v6
        with:
          repository: wikimedia/mediawiki
          ref: ${{ matrix.mediawiki }}
      - name: Setup Extension
        uses: actions/checkout@v6
        with:
          path: extensions/${{ env.EXTNAME }}
      - name: Setup Composer
        run: |
          echo '{"extra":{"merge-plugin":{"include":["extensions/*/composer.json","skins/*/composer.json"]}}}' > composer.local.json
          composer update
          composer update
      - name: Phan
        run: ./vendor/bin/phan -d extensions/${{ env.EXTNAME }} --minimum-target-php-version=8.1 --long-progress-bar

  tests-npm:
    name: Banana tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Setup Extension
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
